---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

Docker weblogic 12.2.1.3:
  stage: deployment test
  script:
    - molecule test -s docker-12.2.1.3
  tags:
    - docker

Docker weblogic 12.1.2:
  stage: deployment test
  script:
    - molecule test -s docker-12.1.2
  tags:
    - docker

Docker weblogic 12.1.1:
  stage: deployment test
  script:
    - molecule test -s docker-12.1.1
  tags:
    - docker

Docker weblogic 10.3.6 jar:
  stage: deployment test
  script:
    - molecule test -s docker-10.3.6-jar
  tags:
    - docker

Docker weblogic 10.3.6 bin:
  stage: deployment test
  script:
    - molecule test -s docker-10.3.6-bin
  tags:
    - docker

AWS weblogic 12.2.1.3:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-12.2.1.3
  tags:
    - delegated

EPC weblogic 12.2.1.3:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-12.2.1.3
  tags:
    - delegated
