---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_major_version: 7
      java_minor_version: 191
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-java/jdk-7u191-linux-x64.tar.gz"
    - role: ansible-role-weblogic
      wls_version: "12.1.1.0"
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/app-servers/weblogic/12.1.1.0/V31344-01.zip"
